name: Git Tag Semver From Label

on:
  workflow_call:
    inputs:
      sha:
        type: string
        description: |
          The commit SHA to tag. Defaults to the GITHUB_SHA.
        required: false
        default: ${{ github.sha }}
    secrets:
      github-token:
        description: |
          The GitHub token utilized to push the tags. Defaults to the GITHUB_TOKEN otherwise.
        required: false
    outputs:
      tags:
        description: A JSON array of tags applied to the HEAD commit.
        value: ${{ jobs.git-tag-semver-from-label.outputs.tags }}

permissions:
  contents: write
  pull-requests: write

jobs:
  get-current-pr:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    outputs:
      pull-request: ${{ steps.get-current-pr.outputs.pr }}
    steps:
      - id: get-current-pr
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        with:
          sha: ${{ inputs.sha }}
      - if: ${{ steps.get-current-pr.outputs.pr_found == 'false' }}
        run: |
          echo "::error::no matching PR found!"
          exit 1
  check-has-semver-label:
    needs:
      - get-current-pr
    permissions:
      pull-requests: write
    uses: infrastructure-blocks/check-has-semver-label-workflow/.github/workflows/check-has-semver-label.yml@v1
    with:
      pull-request: ${{ needs.get-current-pr.outputs.pull-request }}
  git-tag-semver:
    needs:
      - check-has-semver-label
    if: ${{ needs.check-has-semver-label.outputs.matched-label != 'no version' }}
    permissions:
      contents: write
      pull-requests: write
    uses: infrastructure-blocks/git-tag-semver-workflow/.github/workflows/git-tag-semver.yml@v1
    with:
      version: ${{ needs.check-has-semver-label.outputs.matched-label }}
      sha: ${{ inputs.sha }}
    secrets:
      github-token: ${{ secrets.github-token }}
