name: Git Tag Semver From Label

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  git-tag-semver-from-label:
    uses: ./.github/workflows/workflow.yml
    permissions:
      contents: write
      pull-requests: write
    secrets:
      github-token: ${{ secrets.PAT }}
