name: Use Self

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  git-tag-semver-from-label:
    uses: ./.github/workflows/git-tag-semver-from-label.yml
    permissions:
      contents: write
      pull-requests: write
    secrets:
      github-token: ${{ secrets.PAT }}
